version: '3.7'
services:
  php:
    build:
      context: './docker/php/'
    networks:
      - backend
    volumes:
      - ./src:/var/www/html/
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=ma49df
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ma49df
    volumes:
      - ./volumes/mysql:/var/lib/mysql


networks:
  backend:
    driver: bridge
